sudo: required
dist: trusty

language: java

jdk:
  - openjdk8
  - oraclejdk8

install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  email: false

before_install:
 - chmod +x gradlew
