sudo: required
dist: trusty

language: java

jdk:
  - openjdk8
  - oraclejdk8

install: ./gradlew setupCIWorkspace
script: ./gradlew build

notifications:
  email: false

before_install:
 - git submodule update --init --recursive
 - chmod +x gradlew

git:
  submodules: true

